services:
  postgres:
    image: postgres:16
    container_name: exercice11-db
    environment:
      POSTGRES_DB: exercice11
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"